ipc = on
splash = false

preload = /home/bigdihh/.local/share/dotfiles/current/background
wallpaper {
    monitor = 
    path = /home/bigdihh/.local/share/dotfiles/current/background
    fit_mode = cover
}
